[versions]
# --- Build & Kotlin ---
agp = "8.10.0"
kotlin = "2.0.21"
ksp = "2.0.21-1.0.28"
ktlint = "12.1.1"

# --- Android Core & Lifecycle ---
coreKtx = "1.17.0"
coreSplashscreen = "1.2.0"
lifecycleRuntimeKtx = "2.10.0"
lifecycleRuntimeCompose = "2.10.0"
credentials = "1.6.0"

# --- Compose (UI) ---
activityCompose = "1.12.2"
composeBom = "2025.09.01"
navigationCompose = "2.9.6"

# --- Dependency Injection (Hilt) ---
hilt = "2.56.2"
hiltNavigationCompose = "1.3.0"

# --- Network (Retrofit & OkHttp) ---
retrofit = "3.0.0"
okhttpBom = "4.12.0"
okhttp = "4.12.0"
loggingInterceptor = "4.12.0"
kotlinxSerializationJson = "1.7.3"
converterKotlinxSerialization = "3.0.0"

# --- Image Loading (Coil) ---
coilCompose = "2.7.0"

# --- Local Storage (DataStore) ---
datastorePreferences = "1.2.0"

# --- Utils ---
timber = "5.0.1"
immutable = "0.4.0"

# --- Testing ---
junit = "4.13.2"
mockito = "5.23.0"
coroutinesTest = "1.9.0"
junitVersion = "1.3.0"
espressoCore = "3.7.0"

# --- Kakao ---
kakao = "2.23.1"
lottieCompose = "6.6.6"

# --- Google Identity ---
googleId = "1.2.0"

# --- Firebase ---
firebaseBom = "34.15.0"
google-services = "4.5.0"


[libraries]
# --- Android Core ---
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-core-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "coreSplashscreen" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-lifecycle-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "lifecycleRuntimeCompose" }
androidx-credentials = { group = "androidx.credentials", name = "credentials", version.ref = "credentials" }
androidx-credentials-play-services-auth = { group = "androidx.credentials", name = "credentials-play-services-auth", version.ref = "credentials" }

# --- Compose (UI) ---
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationCompose" }

# --- Dependency Injection (Hilt) ---
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-android-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }
androidx-hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hiltNavigationCompose" }

# --- Network & Serialization ---
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
converter-kotlinx-serialization = { group = "com.squareup.retrofit2", name = "converter-kotlinx-serialization", version.ref = "converterKotlinxSerialization" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
okhttp-bom = { group = "com.squareup.okhttp3", name = "okhttp-bom", version.ref = "okhttpBom" }
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "loggingInterceptor" }

# --- Image Loading (Coil) ---
coil-compose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coilCompose" }

# --- Local Storage ---
androidx-datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastorePreferences" }

# --- Utils ---
timber = { group = "com.jakewharton.timber", name = "timber", version.ref = "timber" }
immutable = { group = "org.jetbrains.kotlinx", name = "kotlinx-collections-immutable", version.ref = "immutable" }

# --- Testing ---
junit = { group = "junit", name = "junit", version.ref = "junit" }
mockito-core = { group = "org.mockito", name = "mockito-core", version.ref = "mockito" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "coroutinesTest" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }

# -- Kakao ---
kakao-user = { group = "com.kakao.sdk", name = "v2-user", version.ref = "kakao" }
lottie-compose = { group = "com.airbnb.android", name = "lottie-compose", version.ref = "lottieCompose" }

# --- Google Identity ---
googleid = { group = "com.google.android.libraries.identity.googleid", name = "googleid", version.ref = "googleId" }

# --- Firebase ---
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebaseBom" }
firebase-messaging = { group = "com.google.firebase", name = "firebase-messaging" }

[plugins]
# --- Android & Kotlin ---
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

# --- Tools & Libs ---
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
google-services = { id = "com.google.gms.google-services", version.ref = "google-services" }
